services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
