"""empty message

Revision ID: 44699b664e5e
Revises: bda684c88a35
Create Date: 2024-11-09 15:19:23.497410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44699b664e5e'
down_revision: Union[str, None] = 'bda684c88a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("ALTER TABLE users ALTER COLUMN telegram_id TYPE INTEGER USING telegram_id::integer")
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    # op.execute("ALTER TABLE users ALTER COLUMN telegram_id TYPE INTEGER USING telegram_id::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
